### ISSUE TITLE
df_status() está desactualizada

### ISSUE THREAD

**Issue by chechoid** [pablo14/libro-vivo-ciencia-datos#2]
Hola @pablo14 y @sicarul, todo bien?

Estaba repasando el capítulo de análisis exploratorio de datos y vi que aún continua publicada la función `df_status()` cuando en la versión 1.9.4 del paquete la función actualmente se llama `status()`.

**Comment by pablo14** [comment]
Gracias Sergio! Ya lo tengo modificado para que salga en el próximo release :)
